name: parkinson_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pinput: ^3.0.1
  easy_date_timeline: ^1.0.5
  flutter_slidable: ^3.1.0
  http: ^1.1.0
  flutter_bloc: ^8.1.5
  provider: ^6.1.2
  day_picker: ^2.2.0
  image_picker: ^1.0.8
  http_parser: ^4.0.2
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  percent_indicator: ^4.2.3
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  intl: ^0.19.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/

flutter_native_splash:
  color: "#ffffff" # Background color for the splash screen
  image: assets/images/splash.png # Path to your splash screen image
  android: true # Generate Android splash screen
  ios: true # Generate iOS splash screen
  web: false # Disable web splash screen
  android_12:
    image: assets/images/splash.png # Path to your splash screen image for Android 12
    icon_background_color: "#ffffff" # Background color for the icon in Android 12

